version: 0.2

env:
  secrets-manager:
    ACCESS_ID: "aws-access:AWS_ACCESS_KEY_ID"
    SECRET_ACCESS: "aws-access:AWS_SECRET_ACCESS_KEY"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${MY_AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/mywebserver
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...

      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id aws-access)
      - ACCESS_ID=$(echo $SECRET_JSON | jq -r '.SecretString' | jq -r .AWS_ACCESS_KEY_ID)
      - SECRET_ACCESS=$(echo $SECRET_JSON | jq -r '.SecretString' | jq -r .AWS_SECRET_ACCESS_KEY)
      - echo $ACCESS_ID
      - echo $SECRET_ACCESS
     # - docker build -t $REPOSITORY_URI:latest .
      - docker build -t $REPOSITORY_URI:latest . --build-arg ACCESS_ID=${ACCESS_ID} --build-arg SECRET_ACCESS=${SECRET_ACCESS}
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"web-container02","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json